FROM docker.sunet.se/openjdk-jre-luna:luna7.4-jre11

# Install pkcs11-tool
RUN apt-get update && apt-get install -y pcscd libccid libpcsclite-dev libssl-dev libreadline-dev autoconf automake build-essential docbook-xsl xsltproc libtool pkg-config && \
    wget https://github.com/OpenSC/OpenSC/releases/download/0.21.0/opensc-0.21.0.tar.gz && \
    tar xfvz opensc-*.tar.gz && \
    cd opensc-0.21.0 && \
    ./bootstrap && ./configure --prefix=/usr --sysconfdir=/etc/opensc && \
    make && make install && \
    cd .. && rm -rf opensc*

# Setup softhsm
RUN rm -rf /var/lib/softhsm/tokens && mkdir /var/lib/softhsm/tokens

ADD target/signservice-ca-1.0.0-SNAPSHOT.jar /app.jar
COPY src/main/resources/cfg/start.sh /

ENTRYPOINT /start.sh

# Main web port
EXPOSE 8080
# HTTPS web port
EXPOSE 8443
# AJP port
EXPOSE 8009
# Management port
EXPOSE 8008
# Internal admin UI port
EXPOSE 8006
