FROM openjdk:11-jre

ADD target/signservice-ca-1.0.0.jar /app.jar

# This ENTRYPOINT enables attachement of a debugger on port 8000. This port is automtically exposed on the docker container.
ENTRYPOINT ["java","-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:8000","-jar","/app.jar"]

# Main web port
EXPOSE 8080
# HTTPS web port
EXPOSE 8443
# AJP port
EXPOSE 8009
# Management port
EXPOSE 8008
# Internal admin UI port
EXPOSE 8006
